name: exemplo_firebase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  gradient_widgets: ^0.6.0
  cached_network_image: ^3.2.0
  geocoding: ^3.0.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  flutter:
    sdk: flutter
  intl: ^0.18.1
  http: ^0.13.6
  geolocator: ^13.0.2
  flutter_animate: ^4.2.0
  glassmorphism: ^3.0.0
  flutter_markdown: ^0.7.4+1
  shared_preferences: ^2.1.0



dev_dependencies:
  flutter_launcher_icons: ^0.13.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  label: "Recolhe.ai"
  min_sdk_android: 21 # android min sdk min:16, default 21
